# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.20"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "4096"
  end
  config.vm.provision :shell, inline: <<-SHELL
    # update apt-get
    sudo apt-get update

    # install ubuntu desktop
    sudo apt-get -y install ubuntu-desktop

    # restart ubuntu
    sudo shutdown -r now
  SHELL
end
